/**
 * axiom-narrative-pulse — HTTP server
 *
 * Serves the latest narrative-pulse snapshot. Snapshot is regenerated by
 * `refresh-snapshot.mjs` (cron); the server only reads + filters.
 *
 * Routes:
 *   GET /api/axiom-narrative-pulse?narrative=&phase=&position=
 *   GET /.well-known/ai-tool/axiom-narrative-pulse.json
 *   GET /health
 *
 * Pricing: x402 ($0.01 USDC on Base). Pass-holders bypass via x-pass-holder
 * header. Verification happens upstream at the Vercel edge — this server
 * trusts the headers it receives.
 */

import http from "node:http";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const PORT = parseInt(process.env.PORT ?? "3458", 10);

const __dir = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dir, "../..");
const MANIFEST_PATH = path.join(REPO_ROOT, ".well-known/ai-tool/axiom-narrative-pulse.json");
const SNAPSHOT_PATH = path.join(__dir, "snapshot.json");

function loadSnapshot() {
  const raw = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf8"));
  const ageMs = Date.now() - new Date(raw.generatedAt).getTime();
  raw.stalenessHours = Math.round((ageMs / 3_600_000) * 10) / 10;
  return raw;
}

function filterSnapshot(snap, { narrative, phase, position }) {
  let narratives = snap.narratives;
  if (narrative) narratives = narratives.filter(n => n.slug === narrative);
  if (phase)     narratives = narratives.filter(n => n.phase === phase);
  if (position)  narratives = narratives.filter(n => n.position === position);
  return { ...snap, narratives };
}

function cors(res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, x-payment, x-pass-holder");
}

function json(res, code, data) {
  cors(res);
  res.writeHead(code, { "Content-Type": "application/json" });
  res.end(JSON.stringify(data, null, 2));
}

const server = http.createServer((req, res) => {
  const [pathname, qs] = (req.url ?? "/").split("?");

  if (req.method === "OPTIONS") { cors(res); res.writeHead(204); res.end(); return; }

  if (pathname === "/health") {
    return json(res, 200, { status: "ok", tool: "axiom-narrative-pulse" });
  }

  if (pathname === "/.well-known/ai-tool/axiom-narrative-pulse.json") {
    try {
      const m = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
      return json(res, 200, m);
    } catch {
      return json(res, 404, { error: "manifest not found" });
    }
  }

  if (pathname === "/api/axiom-narrative-pulse") {
    try {
      const params = Object.fromEntries(new URLSearchParams(qs ?? ""));
      const snap = loadSnapshot();
      const filtered = filterSnapshot(snap, params);
      return json(res, 200, filtered);
    } catch (err) {
      return json(res, 500, { error: err.message });
    }
  }

  return json(res, 404, { error: "not found", routes: [
    "/api/axiom-narrative-pulse",
    "/.well-known/ai-tool/axiom-narrative-pulse.json",
    "/health",
  ]});
});

server.listen(PORT, () => {
  console.log(`axiom-narrative-pulse server → http://localhost:${PORT}`);
});
