// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {AxiomToolPassRenderer} from "../contracts/AxiomToolPassRenderer.sol";

/// @notice Verifies the on-chain renderer's trait selection matches the
/// off-chain JS reference (render.mjs) bit-for-bit. Fixtures generated by:
///   node renderer/render.mjs <id>  (plus a one-off dump script)
contract AxiomToolPassRendererTest is Test {
    AxiomToolPassRenderer internal r;

    function setUp() public {
        r = new AxiomToolPassRenderer();
    }

    struct Fix {
        uint256 id;
        string tier;
        string palette;
        string sigil;
        string sigilCount;
        int16 watermarkAngle;
        uint16 sigilRotation;
    }

    /// Twelve fixtures spanning the supply, including one Rare (id=6) and one
    /// Rare-Twin (id=999) — see fixtures in renderer/render.mjs.
    function _fix(uint256 i) internal pure returns (Fix memory) {
        if (i == 0) return Fix(1,    "Standard", "Ash Blue / Navy",       "Spiral",     "Twin",   22, 65);
        if (i == 1) return Fix(2,    "Standard", "Cream / Sepia",         "Compass",    "Single", -22, 115);
        if (i == 2) return Fix(5,    "Standard", "Ochre / Deep Brown",    "Concentric", "Single", -15, 259);
        if (i == 3) return Fix(6,    "Rare",     "Onyx / Gold",           "Concentric", "Single",  22, 47);
        if (i == 4) return Fix(10,   "Standard", "Cream / Sepia",         "Hatch",      "Single", -15, 268);
        if (i == 5) return Fix(42,   "Standard", "Ash Blue / Navy",       "Spiral",     "Single", -22, 37);
        if (i == 6) return Fix(100,  "Standard", "Ash Blue / Navy",       "Star",       "Single",  22, 229);
        if (i == 7) return Fix(250,  "Standard", "Dusty Rose / Burgundy", "Star",       "Single", -15, 204);
        if (i == 8) return Fix(500,  "Standard", "Cream / Sepia",         "Hatch",      "Single", -15, 106);
        if (i == 9) return Fix(750,  "Standard", "Dusty Rose / Burgundy", "Star",       "Single",  22, 290);
        if (i == 10) return Fix(999, "Rare",     "Onyx / Gold",           "Concentric", "Twin",    15, 195);
        return Fix(1000, "Standard", "Ivory / Forest", "Spiral", "Twin", 15, 217);
    }

    function test_TraitsMatchOffchainReference() public view {
        for (uint256 i = 0; i < 12; i++) {
            Fix memory f = _fix(i);
            (
                string memory tier,
                string memory palette,
                string memory sigil,
                string memory sigilCount,
                int16 wmAngle,
                uint16 sigilRot
            ) = r.traits(f.id);

            assertEq(tier, f.tier, "tier");
            assertEq(palette, f.palette, "palette");
            assertEq(sigil, f.sigil, "sigil");
            assertEq(sigilCount, f.sigilCount, "sigilCount");
            assertEq(wmAngle, f.watermarkAngle, "watermarkAngle");
            assertEq(uint256(sigilRot), uint256(f.sigilRotation), "sigilRotation");
        }
    }

    function test_TokenURIReturnsDataURI() public view {
        string memory uri = r.tokenURI(1);
        bytes memory b = bytes(uri);
        assertGt(b.length, 100, "data uri non-empty");
        // Must start with the JSON data URI prefix.
        assertEq(_substr(b, 0, 29), "data:application/json;base64,", "data uri prefix");
    }

    function test_SVGContainsExpectedMarkers() public view {
        string memory s = r.svg(1);
        assertTrue(_contains(s, "<svg"), "<svg> tag");
        assertTrue(_contains(s, "AXIOM"), "AXIOM text");
        assertTrue(_contains(s, "tool pass"), "tool pass text");
        assertTrue(_contains(s, "0001 / 1000"), "serial");
        assertTrue(_contains(s, "BYPASS x402"), "tagline");
    }

    function test_RareTokenSVGUsesOnyxColors() public view {
        // tokenId 6 is Rare Onyx/Gold per fixtures.
        string memory s = r.svg(6);
        assertTrue(_contains(s, "#0d0d0d"), "paper #0d0d0d");
        assertTrue(_contains(s, "#d4af37"), "ink #d4af37");
    }

    function test_TwinSigilTokenHasMirroredSigil() public view {
        // tokenId 1 has sigilCount=Twin. The right sigil sits at translate(516, ...);
        // the twin's mirror at translate(74, ...). Both must appear.
        string memory s = r.svg(1);
        assertTrue(_contains(s, "translate(516 226)"), "right sigil");
        assertTrue(_contains(s, "translate(74 226)"), "left twin sigil");
    }

    function test_SingleSigilTokenLacksLeftSigil() public view {
        // tokenId 2 has sigilCount=Single.
        string memory s = r.svg(2);
        assertTrue(_contains(s, "translate(516 226)"), "right sigil");
        assertFalse(_contains(s, "translate(74 226)"), "no left sigil for Single");
    }

    function test_OutOfRangeReverts() public {
        vm.expectRevert(bytes("tokenId out of range"));
        r.tokenURI(0);
        vm.expectRevert(bytes("tokenId out of range"));
        r.tokenURI(1001);
    }

    // -- helpers ----------------------------------------------------

    function _substr(bytes memory b, uint256 start, uint256 len) internal pure returns (string memory) {
        bytes memory out = new bytes(len);
        for (uint256 i = 0; i < len; i++) out[i] = b[start + i];
        return string(out);
    }

    function _contains(string memory haystack, string memory needle) internal pure returns (bool) {
        bytes memory h = bytes(haystack);
        bytes memory n = bytes(needle);
        if (n.length == 0 || h.length < n.length) return false;
        for (uint256 i = 0; i <= h.length - n.length; i++) {
            bool ok = true;
            for (uint256 j = 0; j < n.length; j++) {
                if (h[i + j] != n[j]) {
                    ok = false;
                    break;
                }
            }
            if (ok) return true;
        }
        return false;
    }
}
